# .goreleaser.yaml
project_name: printer

builds:
  - main: ./main.go
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

snapshot:
  name_template: "snapshot-{{ .Commit }}"

brews:
  - name: printer
    homepage: "https://github.com/meto2208/printer" 
    description: "A delightful CLI for printing things"
    license: "MIT"
    install: |
      bin.install "printer"
    # Optional: Dependencies for your CLI
    # dependencies:
    #   - "some-dependency"
    # conflicts:
    #   - "another-printer"
    repository:
      owner: meto2208
      name: homebrew-printer
      branch: main