# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Printer < Formula
  desc "A delightful CLI for printing things"
  homepage "https://github.com/meto2208/printer-cli"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meto2208/printer-cli/releases/download/v1.1.1/printer_1.1.1_darwin_amd64.tar.gz"
      sha256 "68c71c96153091944df52c0375af9051d4850a016c891826523c9c49eb3bb4b8"

      def install
        bin.install "printer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meto2208/printer-cli/releases/download/v1.1.1/printer_1.1.1_darwin_arm64.tar.gz"
      sha256 "f86ca41397d3cab9b9d36debb3de238ce03e4ee3a973531f1bbb01868d3fc574"

      def install
        bin.install "printer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meto2208/printer-cli/releases/download/v1.1.1/printer_1.1.1_linux_amd64.tar.gz"
        sha256 "8239c351a71d996964c36493d966a79221c8074c992743dbd515f16ec1f8410e"

        def install
          bin.install "printer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meto2208/printer-cli/releases/download/v1.1.1/printer_1.1.1_linux_arm64.tar.gz"
        sha256 "b6712043ead1cf059c0dfcedc7605b93452f7b835e6fd60e31d34a8448019a52"

        def install
          bin.install "printer"
        end
      end
    end
  end
end
