# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Printer < Formula
  desc "A delightful CLI for printing things"
  homepage "https://github.com/meto2208/printer"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/meto2208/printer-cli/releases/download/v1.1.0/printer_1.1.0_darwin_amd64.tar.gz"
      sha256 "206466fee5d1b7bce60a607bfaa71db20a5ac1d78492d6d5ad925e552ee0c777"

      def install
        bin.install "printer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/meto2208/printer-cli/releases/download/v1.1.0/printer_1.1.0_darwin_arm64.tar.gz"
      sha256 "105d105505a34ffe75cc67b588f35daba407089fd08238fd2eccc46a7620b083"

      def install
        bin.install "printer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meto2208/printer-cli/releases/download/v1.1.0/printer_1.1.0_linux_amd64.tar.gz"
        sha256 "4f6be183c563bf66b159b0fa143af08def412f1b2fff4d2f5783b1819caaffc5"

        def install
          bin.install "printer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/meto2208/printer-cli/releases/download/v1.1.0/printer_1.1.0_linux_arm64.tar.gz"
        sha256 "d3e17d299a03e2a4c658f122a3a2114fb9dcfba5de948dcd9224264a3e96400f"

        def install
          bin.install "printer"
        end
      end
    end
  end
end
